import { atomFamily } from "../core/atom-family";
import { atom } from "../core/atom";
import { selector, asyncSelector } from "../core/selector";
import { selectorFamily, asyncSelectorFamily } from "../core/selector-family";
import { useRecoilState } from "../hooks/use-recoil-state";
import { useRecoilValue } from "../hooks/use-recoil-value";
import { useSetRecoilState } from "../hooks/use-set-recoil-state";
import { useRecoilCallback } from "../hooks/use-recoil-callback";
import {
  ChangeEvent,
  FunctionComponent,
  MouseEvent,
  Suspense,
  useState,
} from "react";
import { waitForAll } from "../core/wait-for-all";

export interface Todo {
  id: string;
  name: string;
  completed: boolean;
}

const initialState: Todo[] = [];

const todosState = atom({
  key: "todos",
  default: initialState,
});

const numTodosState = selector({
  key: "numTodos",
  get: ({ get }) => {
    const todos = get(todosState);
    return todos.filter((todo) => !todo.completed).length;
  },
});

const fooStateFam = atomFamily<string, string>({
  key: "foo-state-fam",
  default: (param) => param,
});

const fooSelector = selector({
  key: "foo-selector",
  get: ({ get }) => get(todosState),
});

const randomNumberSelector = asyncSelector<number, "Crunching numbers...">({
  key: "randomNumberSelector",
  get: async () => {
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return Math.random();
  },
  fallback: "Crunching numbers...",
});

const randomIDSelectorFam = asyncSelectorFamily<
  string,
  string,
  "Fetching ID..."
>({
  key: "randomIDSelectorFam",
  get: (param: string) => async () => {
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return `#${param}.${Math.random()}`;
  },
  fallback: "Fetching ID...",
});

const allIdsAtom = waitForAll([
  randomIDSelectorFam("bob"),
  randomIDSelectorFam("alice"),
]);

const composableAtomFam = atomFamily({
  key: "composed-atom-fam",
  default: (param) => param,
});

const composableAtomFam2 = atomFamily<number, string>({
  key: "composed-atom-fam-2",
  default: (param) => param.length,
});

const composedSelectorFam = selectorFamily<string, string>({
  key: "composed-selector-fam",
  get:
    (param) =>
    ({ get }) =>
      get(composableAtomFam(param)) +
      String(get(composableAtomFam2(param))) +
      " (composed)",
  set:
    (param) =>
    ({ set }, newValue) => {
      set(composableAtomFam(param), newValue);
    },
});

const NewTodo: FunctionComponent = () => {
  const [todoName, setTodoName] = useState("");
  const setTodos = useSetRecoilState(todosState);

  const onChange = (e: ChangeEvent<HTMLInputElement>) => {
    const todoName = e.target.value;
    setTodoName(todoName);
  };

  const onSave = (e: MouseEvent<HTMLInputElement>): void => {
    e.preventDefault();
    setTodos((todoList) => [
      ...todoList,
      {
        //Random Autogenerated ID
        id: Math.random().toString(32).substr(2, 9),
        name: todoName,
        completed: false,
      },
    ]);
  };

  return (
    <div>
      <input type="text" onChange={onChange} />
      <input type="button" value="Add" onClick={onSave} />
    </div>
  );
};

const NumTodos: React.FC = () => {
  const numTodos = useRecoilValue(numTodosState);
  return <div>Active todos: {numTodos}</div>;
};

export const TodoList: React.FC = () => {
  const [todos, setTodo] = useRecoilState(todosState);

  const completeTodo = (e: ChangeEvent<HTMLInputElement>) => {
    const id = e.target.value;
    const index = todos.findIndex((todo) => todo.id == id);
    const todoList = [...todos];
    todoList[index] = {
      ...todoList[index],
      completed: !todoList[index].completed,
    };
    setTodo(() => todoList);
  };

  const todoList = todos
    .filter((todo) => !todo.completed)
    .map((todo) => (
      <li key={todo.id}>
        {todo.name}
        <input type="checkbox" value={todo.id} onChange={completeTodo} />
      </li>
    ));
  return <ul>{todoList} </ul>;
};

export const JotaiApp = () => {
  const fam1 = useRecoilValue(fooStateFam("foo-1"));
  const [fam2, setFam2] = useRecoilState(fooStateFam("2"));
  const sel1 = useRecoilValue(fooSelector);
  const alertValue = useRecoilCallback(({ snapshot }) => async () => {
    alert(`${(await snapshot.getPromise(fooSelector)).map((x) => x.name)}`);
  });
  const setMeToCarol = useRecoilValue(composedSelectorFam("set-me-to-carol"));
  const derived = useRecoilValue(
    composedSelectorFam(setMeToCarol.split(" ")[0]),
  );
  const setIdToCarol = useRecoilCallback(({ set }) => async () => {
    set(composedSelectorFam("set-me-to-carol"), "carol");
  });
  const randNum = useRecoilValue(randomNumberSelector);
  const ids = useRecoilValue(allIdsAtom);
  console.log(ids);
  return (
    <Suspense>
      <div className="App">
        <NewTodo />
        <TodoList />
        <NumTodos />
        <br />
        {fam1}
        <br />
        <button
          onClick={() => setFam2((prev: string) => String(Number(prev) + 1))}
        >
          foo-{fam2}
        </button>
      </div>
      <br />
      <button onClick={alertValue}>alert selector value – {sel1.length}</button>
      <br />
      <button onClick={setIdToCarol}>set carol</button>
      {setMeToCarol} {"->"} {derived}
      <br />
      Random number: {randNum}
      <br />
      {"["}
      {ids.map((id, i) => (
        <>
          <span key={`id${i}`}>{id}</span>,{" "}
        </>
      ))}
      {"]"}
    </Suspense>
  );
};
